apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elfin
  namespace: kube-system
  labels:
    k8s-app: elfin
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: elfin
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: elfin
        image: registry.cn-beijing.aliyuncs.com/troy-image/elfin:v0.2
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
        - name: npd-config
          mountPath: /config
        - name: proc
          mountPath: /proc
      hostNetwork: true
      volumes:
      - name: log
        hostPath:
          path: /var/log/
      - name: proc
        hostPath:
          path: /proc/
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: npd-config
        configMap:
          name: npd-config
      serviceAccountName: node-problem-detector
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - key: "CriticalAddonsOnly"
        operator: "Exists"


